AWSTemplateFormatVersion: 2010-09-09
Description: AWS DevOps Capstone

Parameters:
  VPCCidr:
    Description: VPC Cidr
    Type: String
  Tag:
    Description: Project tag
    Type: String
  PublicSubnetCidr1:
    Description: public subnet cidr 1
    Type: String
  PublicSubnetCidr2:
    Description: public subnet cidr 2
    Type: String
  PrivateSubnetCidr1:
    Description: Private subnet cidr 1
    Type: String
  PrivateSubnetCidr2:
    Description: Private subnet cidr 2
    Type: String

Resources:
  AwsDevopsCapstoneVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VPCCidr
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: project
          Value: !Ref Tag

  AwsGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: project
          Value: !Ref Tag

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref AwsDevopsCapstoneVPC
      InternetGatewayId: !Ref AwsGateway

  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [0, !GetAZs ""]
      VpcId: !Ref AwsDevopsCapstoneVPC
      CidrBlock: !Ref PublicSubnetCidr1
      MapPublicIpOnLaunch: true
      Tags:
        - Key: project
          Value: !Ref Tag

  PublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [1, !GetAZs ""]
      VpcId: !Ref AwsDevopsCapstoneVPC
      CidrBlock: !Ref PublicSubnetCidr2
      MapPublicIpOnLaunch: true
      Tags:
        - Key: project
          Value: !Ref Tag

  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [0, !GetAZs ""]
      VpcId: !Ref AwsDevopsCapstoneVPC
      CidrBlock: !Ref PrivateSubnetCidr1
      MapPublicIpOnLaunch: true
      Tags:
        - Key: project
          Value: !Ref Tag

  PrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [1, !GetAZs ""]
      VpcId: !Ref AwsDevopsCapstoneVPC
      CidrBlock: !Ref PrivateSubnetCidr2
      MapPublicIpOnLaunch: true
      Tags:
        - Key: project
          Value: !Ref Tag

  PublicRTB:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref AwsDevopsCapstoneVPC

  PublicRouteAssoc:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet1
      RouteTableId: !Ref PublicRTB

  PublicRouteAssoc2:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet2
      RouteTableId: !Ref PublicRTB

  ConnectInternetGatewayRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PublicRTB
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref AwsGateway

Outputs:
  VPCId:
    Description: VPC id
    Value: !Ref AwsDevopsCapstoneVPC
    Export:
      Name: VPCId

  PublicSubnet1:
    Description: public subnet 1
    Value: !Ref PublicSubnet1
    Export:
      Name: PublicSubnet1

  PublicSubnet2:
    Description: public subnet 2
    Value: !Ref PublicSubnet2
    Export:
      Name: PublicSubnet2